### ISSUE TITLE
Installation warning

### ISSUE THREAD

**Issue by David-Baron** [timschofield/webERP#186]
Warning when install:
`Deprecated: Optional parameter $NewSQL declared before required parameter $DBType is implicitly treated as a required parameter in C:...\webERP-master\install\index.php on line 1092`
the function : 
`function PopulateSQLData($NewSQL=false,$Demo=false,$db,$DBType,$NewDB = false)`
will be : 
`function PopulateSQLData($NewSQL = false, $Demo=false, $db = null, $DBType = null, $NewDB = false)`
or : 
`function PopulateSQLData($db, $DBType, $NewSQL = false, $Demo = false, $NewDB = false)`

**Comment by timschofield** [comment]
Hi, is this from the latest release (4.15.2) or from the latest code from the master branch on github?

Thanks
Tim

**Comment by David-Baron** [comment]
From the master branch

**Comment by timschofield** [comment]
I have rewritten the installer that is in the master branch now. Would be great if you could test it.

Thanks
Tim

**Comment by David-Baron** [comment]
Sorry but I will not be using this app, it has too many things wrong with it, so you will not get any feedback for your tests.

**Comment by timschofield** [comment]
OK, no problem.
Seems curious that you won't test whether the things that were wrong have benn fixed, because of the things that are wrong, but that is your prerogative.

Thanks for your interest anyway
Tim
