### ISSUE TITLE
Commit 8395 does not install database

### ISSUE THREAD

**Issue by efeoli** [timschofield/webERP#198]
Hi,
I was waiting for your installer rewritted script, since the application could not be installed when clicking the INSTALL button.

Despite the improvements the files get installed but not  the database.

Enrique

**Comment by timschofield** [comment]
Hello Enrique,

The changes committed yesterday were just some minor fixes that happened in a general sweep of the code. The new installer will be loaded up later today I hope. I will let you know when, and it would be great if you could test again.

Tim

**Comment by timschofield** [comment]
The new installer is now in the master branch. I would really appreciate it if you could test on your system.

Thanks
Tim

**Comment by efeoli** [comment]
Hello Tim.
Thank you for letting me know about the latest master.

It gets to the database credentials, but it will accept the data. Tried repeatedly.

Attachments might help.
Enrique 



![Captura de pantalla_25-10-2024_103115_kwa bioacyl com after](https://github.com/user-attachments/assets/7fc7e02d-d16a-4860-bdf1-56a707f34609)
![Captura de pantalla_25-10-2024_102628_kwa bioacyl com](https://github.com/user-attachments/assets/5f771738-4e32-4fa3-a230-1c30e6247947)

**Comment by efeoli** [comment]
I clarify: it will not accept data

**Comment by efeoli** [comment]
Also images are diproportionatelly large and disturbs format for data to be eneterd and it is not what goes where.

**Comment by timschofield** [comment]
It looks like the css isn't applying. Can you try ctrl-f5 in the browser to force a css reload.

Tim

**Comment by efeoli** [comment]
Yes it did loas the correct css and the procedure went through, but it loaded only 57 tables of the database ínstead of 175.
Enrique

**Comment by efeoli** [comment]
Not it will perform upgrade to a 4.15.2 database. It gets stuck at steps 5,6,7.
![Screenshot 2024-10-25 at 12-23-51 Database Upgrade](https://github.com/user-attachments/assets/f510e2d0-7192-4f5c-9295-820be87e14fd)

**Comment by efeoli** [comment]
These are the 57 tables that it creatres.
![Captura de pantalla_25-10-2024_13748_da4613 squidix net](https://github.com/user-attachments/assets/7f0f1ddb-a0f2-4148-ab10-f3b0a980d13b)

**Comment by timschofield** [comment]
I have just pushed two files
install/tables/jnltmpldetails.sql
install/tables/jnltmplheader.sql

Can you try downloading them and trying again?

Tim

**Comment by efeoli** [comment]
It only improved installing 60 tablea and the last one is “modules”.

Enrique

**Comment by efeoli** [comment]
I also the notice of the 5,6,7 steps to go attached above.

**Comment by timschofield** [comment]
That's very strange as the 60th table is labelfields.

Did you get any error message?

**Comment by efeoli** [comment]
No error message.

Would you like a snapshot of tables?

**Comment by timschofield** [comment]
Yes please.
I ran the installer with mysql mode set as STRICT_TRANS_TABLES and it threw a couple of errors that I have corrected and pushed.

Are you deleting the database between attempts?

**Comment by efeoli** [comment]
I was emptying the database. I will delete and rey again.

We are 6 hours earlier in Costa Rica. I will be available tomorrow in case you will need further testimg.
![Captura de pantalla_25-10-2024_153658_da4613 squidix net](https://github.com/user-attachments/assets/bd62d9af-54e7-44e8-a406-88d1563b0928)

**Comment by efeoli** [comment]
Success!

I comment tomorrow on how it is working.

**Comment by timschofield** [comment]
Glad it now works for you.

I ran the installer again with everything (web server/mysql/PHP) set on their most severe settings. Found 3 more errors that I have now fixed and uploaded
