### ISSUE TITLE
The WO order ready to produce in manufacturing module is still absent. However, this function may be reached form “Commonly used scripts” kept in the imported database and it is fully functional at  https://kwa.bioacyl.com/webERP/WOCanBeProducedNow.php This issue then, would not be crucial for me personally, but would confuse newcomers and it is a pity it being functional and so valuable for manufacturing enterprises but not reachable, simply for a menu problem

### ISSUE THREAD

**Issue by timschofield** [timschofield/webERP#216]

**Comment by efeoli** [comment]
![Captura de pantalla_20-11-2024_104453_erp bioacyl com](https://github.com/user-attachments/assets/81b1f8a8-7120-4a38-9e23-77916bdbac9d)
Tab just above MRP.

**Comment by efeoli** [comment]
Hi All,
I would like to comprise here matters related report tool loading the report file but not shown on the main menu. #218.

Same as for pointing to Z_WOCanNeProducedNow.php that brings forth the script and is functional, the imported reports may also brought forward and are functional.
![Captura de pantalla_4-12-2024_11430_kwa bioacyl com](https://github.com/user-attachments/assets/78de3b1b-43c4-44f1-b404-e5073de64dd7)

As expressed earlier webERP is a top app and all these refined features are based on robust coding and although are within the reach of trained users are not so for newcomers. I will continue to emphasize the value of these features until they will be available for everyone.

There is one difference with reports pointed to from the browser to menu tags in that the latter can be marked to and accessed thereafter from Commonly used scripts but the former can’t and untrained users surely will not know how to access.

I simply wish that v5.0 will not miss any of the wonderful features that have been developed in webERP.
Enrique

**Comment by timschofield** [comment]
Hi Enrique, sorry for the delay in fixing this. The script was available to some user roles, but not the sytem administrator role. I have changed the SQL in the installer to include it, and have put in a DB update file for existing users.

Thanks
Tim

**Comment by efeoli** [comment]
Hi Tim,
thank you for taking webERP to PHP 8 environment rather. I known from other applications how difficult that is.

Regarding the WO to produce not showing up, you did solved it with the fix just committed, including the DB update which worked just fine and appears as #10.

Issue should be closed, but I prefer if you do so.

Thank you so much for this.
Enrique

**Comment by timschofield** [comment]
Hi Enrique, thanks for that. I am closing it, but I am happy for you to close issues once you feel they are resolved.

Thanks
Tim
