### ISSUE TITLE
Most of GL reports of balance/statements are not printing PDFs

### ISSUE THREAD

**Issue by timschofield** [timschofield/webERP#224]

**Comment by efeoli** [comment]
Update 
Any mailing that needs a PDF, gives a PCPDF error. The one below is from trying to print an invoice Customer Transaction Inquiries.

![Captura de pantalla_15-12-2024_182540_kwa bioacyl com](https://github.com/user-attachments/assets/b127a7da-75ae-4314-9234-105a68a4e028)
Enrique

**Comment by aingelc12ell** [comment]
For all TCPDF output with $dest in (F, FI, FD) should be real file path. 

I prepended `$_SESSION['reports_dir'] . '/'` to two affected files
