### ISSUE TITLE
text not wrapping in in manual

### ISSUE THREAD

**Issue by dalers** [timschofield/webERP#233]
I accessed the manual from WWW_Users.php (editing a user record) and found the text in the manual wasn't wrapping. I can resize the browser window almost full-screen and some text is still hidden.

![image](https://github.com/user-attachments/assets/c73493e4-5289-4be1-a135-3ae94143ab8b)

**Comment by timschofield** [comment]
Hi Dale, I have uploaded a new version of the manual.css file. You
will need to force the reload of the css with a Ctrl F5

Thanks
Tim

On Wed, 13 Nov 2024 at 23:30, Dale Scott ***@***.***> wrote:
>
> Nevermind... window can be scrolled horizontally.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/
