### ISSUE TITLE
v 4.15.2 SecurityTokens.php: shows undesired code in fields when running with error_reporting = -1 

### ISSUE THREAD

**Issue by pakricard** [timschofield/webERP#243]
Found the reason of the weird behaviour I find in SecurityTokens.php , initially reported in https://github.com/timschofield/webERP/discussions/240#discussioncomment-11274734

![386791134-2f3644fb-f8ed-4d85-b51a-5537e3b36684](https://github.com/user-attachments/assets/3cd392c3-c577-4cdc-8844-65df15babeda)

It is due to error_reporting set to -1

How to replicate it:
Download the standard v 4.15.2 distribution. 
Install it.
Set error_reporting as -1
And you will see this error, besides many Notice or Warning messages)

<img width="1045" alt="image" src="https://github.com/user-attachments/assets/9df82b50-1348-477b-ad34-bf168c020eb2">

I installed a webERP v4.15.2 as it comes from the zip, on: https://ptadu-development.com/TEST/webERP-4.15.2/index.php 
credentials admin/weberp
Running on PHP 8.2.25 with error_reporting = -1
where you can see the error.

While I'm doing this job of bringing my webERP to date, I will keep this installation (as a benchmark). Fell free to use it if you need.

**Comment by timschofield** [comment]
Hi Ricard,

The latest version of SecurityTokens.php should have that fixed

thanks
Tim

**Comment by pakricard** [comment]
Hi Tim:

Tested and now is OK.
