### ISSUE TITLE
GetConfig.php lines 43 to 50

### ISSUE THREAD

**Issue by pakricard** [timschofield/webERP#248]
Do we really need to keep code lines like these lines 43 to 50?

```
	/*
	 check the decimalplaces field exists in currencies - this was added in 4.0 but is required in 4.04 as it is used everywhere as the default decimal places to show on all home currency amounts
	*/
	$Result = DB_query("SELECT decimalplaces FROM currencies",'','',false,false);
	if (DB_error_no()!=0) { //then decimalplaces not already a field in currencies
		$Result = DB_query("ALTER TABLE `currencies`
							ADD COLUMN `decimalplaces` tinyint(3) NOT NULL DEFAULT 2 AFTER `hundredsname`");
	}

```

decimalplaces was added ages ago, and we have this random check here, but does it make sense to keep it (or similar ones)?

My vote is to delete them.

**Comment by dalers** [comment]
I don’t claim to understand this, but it seems the code is to allow for an old db schema. Do I understand correctly? There seems to be an unwritten rule that databases MUST be updated to a newer schema (i.e, old schemas are not supported), and if so, then it would seem code would never have to accommodate an old schema? I.e. this code would be redundant. Am I missing something?

**Comment by pakricard** [comment]
@dalers : Yes, this code fixes the DB in case currencies table doesn't have the decimalplaces field.
If we do it here, why not everywhere? It seems illogical to me. 
And all scripts should assume that the DB version is the proper one for the code, except the "Update Database", of course.

**Comment by dalers** [comment]
Then my vote is also to remove code like this.

What should be the process for making such a change? I think it would be best to complete removing all "old" decimal places code in a development branch for clarity and ease of testing, instead of multiple incremental commits to the master branch. However, I'm not sure if the development branch should be done in a personal fork or in the master repo (i.e. Tim's repo). Maybe the solution depends on how significant the work is and whether there will be multiple developers working simultaneously (in which case a dev branch in the master repo would be the most convenient).

Also, my assumption has been that only @timschofield would commit to the master repo (i.e. Tim's repo) master branch, and everyone else would submit pull requests, but that may not be what Tim has planned. Tim, how do you envision project management working?

**Comment by pakricard** [comment]
Hi @dalers , I think just these lines on the initial post need to be removed

**Comment by dalers** [comment]
Hi @pakricard then I guess it's a simple commit then. Can you submit a pull request to https://github.com/timschofield/weberp from your fork? Do our new permissions from @timschofield give us the ability to accept pull requests? If so, I _could_ accept the pull request but for now and for me personally, I'd prefer Tim continue for a while as the only person who merges into the master branch (i.e. Tim is webERP's Linus Torvalds, who has the final word on what goes into the Linux kernel).

> like these lines 43 to 50?

Is it worth searching the project for similar code ("like these lines")? I expect however you don't mean there are many similar examples in the project, but rather there are many chunks of code that should be deleted, and this is only one example of many and they are all different.

Btw, are you using Filezilla in real time the directory level while you are editing using Notepad++. If all you would want from an IDE is project-level search and replace, Filezilla+Notepad++ seems to be a clean solution without the overhead of NetBeans (or PHPStorm).

**Comment by dalers** [comment]
P.S. I read a recommendation for "sshfs-win" ([https://github.com/winfsp/sshfs-win](https://github.com/winfsp/sshfs-win)). Iiuc, you could use sshfs-win to "mount a remote directory" on your Windows system as a drive letter, and then edit the physical files on your server using Notepad++ on your windows system, and omit filezilla synchronization. I haven't tried it personally though....

**Comment by pakricard** [comment]
This is great!
I managed to commit directly into upstream (a.k.a. Tim's master repository) from my SourceTree. 
Moreover, adding the text “Fixes #xxx” into the commit text closed the issue automatically in GitHub.

So I think Tim's restored my ancient rights into the repository (or were never deleted, and I managed to make them work again).

**Comment by dalers** [comment]
That's great @pakricard ! :-)
