### ISSUE TITLE
AnalysisHorizontalPosition.php on PHP 8.2.25 Warning: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by pakricard** [timschofield/webERP#252]
Hi:
Latest AnalysisHorizontalPosition.php script shows several Warning: Trying to access array offset on value of type null in /weberp/AnalysisHorizontalIncome.php on line 343 and line 375

**Comment by aingelc12ell** [comment]
Hi @pakricard ,

Kindly rebase your copy from the latest so we can properly identify which of the variables are rendered empty or null.

Thanks

**Comment by pakricard** [comment]
Hi @aingelc12ell :
I'm using the latest GitHub files and still get the same warnings:
![image](https://github.com/user-attachments/assets/dbde0ae9-98e0-4398-9644-d020e4380a79)

**Comment by timschofield** [comment]
I have just committed a fix for this, can you check it works?

Thanks for the report,
Tim

**Comment by pakricard** [comment]
Works OK. 
Thanks @timschofield
