### ISSUE TITLE
CustomerReceipt.php on PHP 8.2.25 Warning: Trying to access array offset on value of type null on line 312

### ISSUE THREAD

**Issue by pakricard** [timschofield/webERP#257]
Hi: 
Newest GitHub CustomerReceipt.php shows Warning: Trying to access array offset on value of type null in /weberp/CustomerReceipt.php on line 312 when entering a Customer Receipt

**Comment by aingelc12ell** [comment]
Hello @pakricard ,

Kindly confirm the following:
1. the GLCode is blank
2. the existence of the record in chartmaster table for the accountcode

If the GLCode is blank or that is not in the chartmaster, $MyRow will be empty, hence the error on line 312.

I can commit the fix to ignore the warning, in case the accountcode or the GLCode are intentionally blank or unknown.

**Comment by pakricard** [comment]
Hi @aingelc12ell:
Latest files from GitHub fixed the issue. 
Many thanks!
