### ISSUE TITLE
PcAssignCashToTab.php - SQL syntax error when editing a cash assignment

### ISSUE THREAD

**Issue by andrewcouling** [timschofield/webERP#261]
webERP version: v.4.15.2
PHP version: 7.4
Script: PcAssignCashToTab.php

**Symptom:**
Went I edit a cash assignment and then click accept, I receive the following error message:

> Database Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE counterindex = '149'' at line  #6

There seems to be a similar issue in the demo site, although there is no error message, but after clicking accept the page doesn't render correctly.

**Comment by timschofield** [comment]
Thanks Andrew, I have fixed this, and committed the change

Tim

**Comment by andrewcouling** [comment]
Thanks Tim. I have tested and the issue is solved.

**Comment by timschofield** [comment]
Good to hear Andy.

On Mon, 2 Dec 2024 at 19:08, Andrew Couling ***@***.***> wrote:
>
> Thanks Tim. I have tested and the issue is solved.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/
