### ISSUE TITLE
The installer shows "webERP" on two lines ("web" and "ERP")

### ISSUE THREAD

**Issue by dalers** [timschofield/webERP#276]
Noticed this when performing a DB Update for the new (development) version number

![image](https://github.com/user-attachments/assets/28f3f96e-c343-4bbb-b62b-aa30abb4524f)

**Comment by dalers** [comment]
Hmmm, just noticed the mentioned databaser is incorrect, I'm actually updating "weberp_scc" (the "weberp_test" database exists, but has currently no tables or schema so I know it's not the one being updated).

**Comment by pakricard** [comment]
I fixed it by chance in Login.php (that had the same issue) and footer.php, but I can't test it on Z_UpgradeDatabase.php
