### ISSUE TITLE
WorkOrderEntry.php LIKE statement should be =

### ISSUE THREAD

**Issue by pakricard** [timschofield/webERP#280]
Hi all:
When deleting a WO, we have this check on line 229 of latest GitHub:

```
	$HasTransResult = DB_query("SELECT transno
                                     FROM stockmoves
                                     WHERE (stockmoves.type= 26 OR stockmoves.type=28)
                                             AND reference " . LIKE . " '%" . $_POST['WO'] . "%'");

```
Should it be a = instead of a LIKE?

If we have reference 1234 already in DB and what to delete the 123, we will not be able as 1234 LIKE %123% returns TRUE, but it refers to stockmoves not related to the one we want to check (123)

Is there any special case that I am missing? Or should we go with an = ?

**Comment by timschofield** [comment]
Thanks Ricard, I have committed this change. As you say the old code made no sense. I hope it wasn't my code, but I have an awful feeling it might be :)

Tim

**Comment by pakricard** [comment]
Thanks Tim! Looks OK to me. I close the issue.
