### ISSUE TITLE
Create GLOBAL Budget tab is not working 

### ISSUE THREAD

**Issue by efeoli** [timschofield/webERP#285]
Hi again,
the tab for creating budgets that was previously working now gives the following error:
![Captura de pantalla_6-12-2024_171927_kwa bioacyl com](https://github.com/user-attachments/assets/49c8805c-14fd-42db-afc6-67692782bfde)
Enrique 
PS
Grammarly squeezed in global instead of gl

**Comment by timschofield** [comment]
Thanks, this should be fixed now.

Tim

On Fri, 6 Dec 2024 at 23:24, efeoli ***@***.***> wrote:
>
> Hi again,
> the tab for creating budgets that was previously working now gives the following error:
> Captura.de.pantalla_6-12-2024_171927_kwa.bioacyl.com.jpeg (view on web)
> Enrique
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/

**Comment by efeoli** [comment]
Yes indeed, working fine now. I will close the issue. Thanks.

**Comment by efeoli** [comment]
Closed.
