### ISSUE TITLE
Usage of defaultgl field on suppliers table

### ISSUE THREAD

**Issue by pakricard** [timschofield/webERP#286]
### Discussed in https://github.com/timschofield/webERP/discussions/279

<div type='discussions-op-text'>

<sup>Originally posted by **pakricard** December  6, 2024</sup>
Hi all:

Regarding the field defaultgl on the suppliers table:

It was added by @timschofield on 19/06/2018 on commit 01898ee, and it refers to http://www.weberp.org/forum/showthread.php?tid=8169&pid=14931#pid14931 but now that the forum is gone there is no context.

Commit message reads: "Ensure that when entering a GL suppliers invoice the default account is pre-selected"

I think we should have a "None" by default, to be compatible with regular suppliers that do not need this functionality

</div>

**Comment by timschofield** [comment]
Well I was working on the basis that most GL supplier Invoices would be for the same GL code. It would be tiresome to have to scroll down to that code each time you entered an invoice to that supplier. It seemed sensible to do it this way. If they weren't for the same GL code, you would still have to scroll to find the code as if there wasn't a default. If the supplier didn't have GL invoices then nothing would happen.

I would have no problem if someone wanted to code a default of 'none'. You might need to look at the database field which has a default value of  '1'.

Thanks
Tim
