### ISSUE TITLE
Installer Database Name & Username input fields maxlength

### ISSUE THREAD

**Issue by andrewcouling** [timschofield/webERP#289]
I'm not able to complete an installation of the latest code because the Database Name & Username input fields in the installer have maxlength character limits of 16.
In my shared hosting environment database names and usernames can have up to 32 characters. The one I'm trying to use has 24, which includes 12 numeric characters which are automatically appended to the chosen name by the hosting control panel.

**Comment by timschofield** [comment]
Thanks for the report, I have updated these fields to 32 characters.

Thanks
Tim

**Comment by andrewcouling** [comment]
Resolved. Thanks Tim.
