### ISSUE TITLE
A blank screen for users maintenance is obtained commit 8498

### ISSUE THREAD

**Issue by efeoli** [timschofield/webERP#296]
Hi Tim,
the title is descriptive of the issue.
![Captura de pantalla_12-11-2024_11849_kwa bioacyl com](https://github.com/user-attachments/assets/bc3dac24-8504-48a1-b1a4-a80430b57a10)

Enrique

**Comment by timschofield** [comment]
Hi Enrique, does this happen when you first select the menu option, or when you click to display the graph?

Tim

**Comment by efeoli** [comment]
Tim,
it is when selecting the menu option. Also it is in database updated version. I didn’t try in demo data install.
Enrique

**Comment by efeoli** [comment]
This is the server’s log:
![Captura de pantalla_10-12-2024_13554_da4613 squidix net](https://github.com/user-attachments/assets/049f9109-c0b6-47eb-a8dc-f335f6342b2f)
![Captura de pantalla_10-12-2024_13554_da4613 squidix net](https://github.com/user-attachments/assets/ae3454e1-76b3-4c06-9037-ce684955f840)

It looks to me as errors related to Concrete5.


I have been noticing differences from the demo after loading a 4.15.2 database. While working in the demo the performance varies after update sometimes.
Enrique

**Comment by timschofield** [comment]
@dalers do you have the php-gd extension loaded?

**Comment by timschofield** [comment]
@efeoli I'm not sure I understand. Do you use the Concrete CMS?
I'm not sure why your webERP should be trying to call a concrete-cms script.

Tim

**Comment by efeoli** [comment]
Sorry about the mixup of screenshots. I have not been able to access GitHub from my desktop because the email sent to verify identity never arrives. I have to work from my phone, which is limiting and liable of confusion.

The sales graph is working just fine.
Enrique

**Comment by dalers** [comment]
@timschofield php-gd is loaded.

```
dale@whizzer:~ $ php -m
[PHP Modules]
bcmath
bz2
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
gmp
hash
iconv
imagick
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
soap
sodium
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

dale@whizzer:~ $
```

**Comment by timschofield** [comment]
Sorry Enrique, are you saying the problem is solved, or is there a
problem with Users maintenance? If ws, is it WWW_Users.php or
UserSettings.php?

thanks
Tim

On Tue, 10 Dec 2024 at 20:19, efeoli ***@***.***> wrote:
>
> Sorry about the mixup of screenshots. I have not been able to access GitHub from my desktop because the email sent to verify identity never arrives. I have to work from my phone, which is limiting and liable of confusion.
>
> The sales graph is working just fine.
> Enrique
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/

**Comment by efeoli** [comment]
We use a VPS and the log is for the entire server. We use many other applications on the VPS and webERP has performed in just an environment for over a decade.

My intention is to help and I am so sorry confusion has derived from my reports.

However, I can asure that sometimes performance changes after a database updated.
Enrique

**Comment by timschofield** [comment]
Very strange, imagecreate() is a php-gd function.


On Tue, 10 Dec 2024 at 20:28, Dale Scott ***@***.***> wrote:
>
> @timschofield php-gd is loaded.
>
> ***@***.***:~ $ php -m
> [PHP Modules]
> bcmath
> bz2
> Core
> ctype
> curl
> date
> dom
> exif
> fileinfo
> filter
> gd
> gettext
> gmp
> hash
> iconv
> imagick
> imap
> intl
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcre
> PDO
> pdo_mysql
> pdo_pgsql
> pdo_sqlite
> Phar
> posix
> Reflection
> session
> SimpleXML
> soap
> sodium
> SPL
> sqlite3
> standard
> sysvsem
> tokenizer
> xml
> xmlreader
> xmlrpc
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib
>
> [Zend Modules]
> Zend OPcache
>
> ***@***.***:~ $
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/

**Comment by timschofield** [comment]
Enrique, pleased rest assured that your reports are very helpful.

If I occasionally get confused it is often my fault, so if it is sometimes somebody elses fault then it just evens things up :)

**Comment by efeoli** [comment]
The issue regards WWW_Users.php and selecting this from main menu is when you get the blank screen.
Enrique

**Comment by timschofield** [comment]
Hi Enrique, what is $AllowDemoMode set to in your config.php?

Thanks
Tim

On Tue, 10 Dec 2024 at 20:35, efeoli ***@***.***> wrote:
>
> The issue regards WWW_Users.php and selecting this from main menu is when you get the blank screen.
> Enrique
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/

**Comment by efeoli** [comment]
Tim,
It is set to “True”.
Enrique

**Comment by efeoli** [comment]
YES, it is correct.
Issue solved and I will close the issue.
Thank you so much.

**Comment by efeoli** [comment]
Issue solved.

**Comment by dalers** [comment]
@timschofield 

> Very strange, imagecreate() is a php-gd function.

My Sales Graph issue was a red herring and completely unrelated. You were correct guessing gd was not loaded.

gd is loaded in my production server, but I was using XAMPP for local testing and it does not have gd loaded. Editing the XAMPP php.ini to load gd resolved the issue. Doh!
