### ISSUE TITLE
Reorder Level Reporting "Top Sales Items List" shows weberp_test in heading

### ISSUE THREAD

**Issue by dalers** [timschofield/webERP#301]
I'm thinking "weberp_test" must be an error as I am not logged into the weberp_test db nor is there even one on the server.

Access [Main Menu > Inventory > Inquiries and Reports > Reorder Level] and click [View]

Perhaps it's hard-coded somewhere. I can investigate why if someone can point me in the likely right direction.

![image](https://github.com/user-attachments/assets/568d0993-5f5f-4738-b5ac-3ba4d59fe31b)

**Comment by andrewcouling** [comment]
It seems strange that in you screenshot, the page URL is TopItems.php, but the page title (top left) is from ReorderLevel.php

**Comment by timschofield** [comment]
The reorder level reporting error was down to me copy and pasting some code, and then not changing these references. I have fixed this

@dalers what is the company name that is in the companies table in the database?

Tim

**Comment by dalers** [comment]
> @dalers what is the company name that is in the companies table in the database?

weberp_scc

**Comment by timschofield** [comment]
Hi Dale, this isn't the subdirectory, or the DB name.

The company name in the companies table is:
![TopItems](https://github.com/user-attachments/assets/fb67b7ed-a039-4aad-a859-5729e48c1a2d)
and this is what appears in the TopItems.php report
![TopItems2](https://github.com/user-attachments/assets/d78aaed1-7208-4872-a137-5b5588140e95)

Is this not what happens with you?
Tim
