### ISSUE TITLE
Inconsistencies in GetPrice.inc with 0000-00-00 and 9999-12-31 dates

### ISSUE THREAD

**Issue by pakricard** [timschofield/webERP#304]
Hi all:

I am confused with this one, as it seems very obvious to be there since June 2017. 
Context: This is the last bit to bring my old 4.13.1 into 4.15.2, before attacking v5 changes. 

On file sql/upgrade4.13.1-4.14.sql, line 15:
```
-- Convert prices to use non- SQL mode specific end date we will have a year 10000 problem but its a way off!:
UPDATE prices SET enddate='9999-12-31' WHERE enddate='0000-00-00';
```
So, changing the prices table with no end date from 0000-00-00 to 9999-12-31, affecting all current prices.

But some instances of 0000-00-00 still exist in GetPrice.inc:
Lines 59-71:
```
				$SQL = "SELECT prices.price,
							   prices.startdate
						FROM prices,
							debtorsmaster
						WHERE debtorsmaster.salestype=prices.typeabbrev
							AND debtorsmaster.debtorno='" . $DebtorNo . "'
							AND prices.stockid = '" . $StockID . "'
							AND prices.currabrev = debtorsmaster.currcode
							AND prices.debtorno=debtorsmaster.debtorno
							AND prices.branchcode=''
							AND prices.startdate<=CURRENT_DATE
							AND prices.enddate='0000-00-00'
						ORDER BY prices.startdate DESC";
```
Line 93-104:
```
						$SQL = "SELECT prices.price,
									   prices.startdate
								FROM prices,
									debtorsmaster
								WHERE debtorsmaster.salestype=prices.typeabbrev
									AND debtorsmaster.debtorno='" . $DebtorNo . "'
									AND prices.stockid = '" . $StockID . "'
									AND prices.debtorno=''
									AND prices.currabrev = debtorsmaster.currcode
									AND prices.startdate<=CURRENT_DATE
									AND prices.enddate='0000-00-00'
								ORDER BY prices.startdate DESC";
```
Line 127-138:
```
								$SQL = "SELECT prices.price,
											 prices.startdate
										FROM prices,
											debtorsmaster
										WHERE prices.stockid = '" . $StockID . "'
											AND prices.currabrev = debtorsmaster.currcode
											AND debtorsmaster.debtorno='" . $DebtorNo . "'
											AND prices.typeabbrev='" . $_SESSION['DefaultPriceList'] . "'
											AND prices.debtorno=''
											AND prices.startdate<=CURRENT_DATE
											AND prices.enddate='0000-00-00'
										ORDER BY prices.startdate DESC";
```
Line 155-162
```
										$SQL = "SELECT max(pricematrix.price) FROM pricematrix,
															debtorsmaster
												WHERE pricematrix.stockid = '" . $StockID . "'
													AND pricematrix.currabrev = debtorsmaster.currcode
													AND pricematrix.salestype = debtorsmaster.salestype
													AND pricematrix.quantitybreak >= '" . $OrderLineQty . "'
													AND pricematrix.startdate<= CURRENT_DATE
													AND pricematrix.enddate='0000-00-00'";
```

This one is working against the table pricematrix, so I guess we should have a 
`UPDATE pricematrix SET enddate='9999-12-31' WHERE enddate='0000-00-00';
`
somewhere but it is not.

Also:
- api/api_stock.php
- Z_POSDataCreation.php 
- PDFPriceList.php
- PDFPrintLabel.php
- PricesBasedOnMarkUp.php
- PricesByCost.php
- Prices_Customer.php
- SelectProduct.php
have SQL related to prices that use 0000-00-00 

On the other hand: 
- install\tables\bom.sql
- install\tables\pricematrix.sql
- install\tables\prices.sql
- PriceMatrix.php
- Prices.php
have SQL related to prices that use 9999-12-31

Users that executed sql/upgrade4.13.1-4.14.sql back in the day, will get inconsistent or wrong prices as getPrice() function gets called and compares against 0000-00-00

My main question is: Which is the right one: 0000-00-00 or 9999-12-31?

Seems too obvious to be still here 7 years after, maybe (hopefully) I am missing something simple that sorts it out.

**Comment by pakricard** [comment]
I have thought about it and there Getprice.inc has many repeated (a.k.a. useless) SQL queries.

Now that 0000-00-00 has become 9999-12-31, there is no need to do 2 SQL queries for every possible setup price:

- price per customer and branch, 
- price per customer, 
- no specific pricing use the customers normal price list but look for special limited time prices with specific end date
- default salestype/price

I think one query should be enough as the previous condition prices.enddate='0000-00-00' is currently included in prices.enddate>=CURRENT_DATE if enddate is 9999-12-31

So, we could remove 4 SQL queries. Simpler and faster.

Regarding 
`UPDATE pricematrix SET enddate='9999-12-31' WHERE enddate='0000-00-00'; `
I think we should implement it too (for consistency) and then the queries from lines 144 and 155 could be simplified too into one single SQL query.

All the scripts still using 0000-00-00 should be modified to use 9999-12-31

If everybody is OK with this, I can take care of this simplification. 

![image](https://github.com/user-attachments/assets/f0e55213-862c-42b8-bdb9-6cd75d459baa)

@timschofield As you were the last one to work on this file 4 years ago, do these proposed changes make sense to you?

Or is there any cases where we need the 10 SQL queries to be executed?

**Comment by timschofield** [comment]
I don't remember my intentions exactly, but I do remember testing
every single scenario and it was mind bending at times. I think in the
end I simplified the SQL by making multiple queries rather than
combining. This was inefficient but it gave me the right answer in
every scenario I could think up. If you feel that you have tested it
thoroughly and are happy, then go for it. I trust you to make the
right judgement call Ricard.

Tim


On Fri, 13 Dec 2024 at 07:56, pakricard ***@***.***> wrote:
>
> I have thought about it and there Getprice.inc has many repeated (a.k.a. useless) SQL queries.
>
> Now that 0000-00-00 has become 9999-12-31, there is no need to do 2 SQL queries for every possible setup price:
>
> price per customer and branch,
> price per customer,
> no specific pricing use the customers normal price list but look for special limited time prices with specific end date
> default salestype/price
>
> I think one query should be enough as the previous condition prices.enddate='0000-00-00' is currently included in prices.enddate>=CURRENT_DATE if enddate is 9999-12-31
>
> So, we could remove 4 SQL queries. Simpler and faster.
>
> Regarding
> UPDATE pricematrix SET enddate='9999-12-31' WHERE enddate='0000-00-00';
> I think we should implement it too (for consistency) and then the queries from lines 144 and 155 could be simplified too into one single SQL query.
>
> All the scripts still using 0000-00-00 should be modified to use 9999-12-31
>
> If everybody is OK with this, I can take care of this simplification.
>
> image.png (view on web)
>
> @timschofield As you were the last one to work on this file 4 years ago, do these proposed changes make sense to you?
>
> Or is there any cases where we need the 10 SQL queries to be executed?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/

**Comment by timschofield** [comment]
Hi Ricard, I think you need to use DB_affected_rows() rather than DB_num_rows() in 12.sql.

thanks
Tim

**Comment by pakricard** [comment]
Hi @timschofield : 
Thanks for pointing it out. 
DB_num_rows() was wrong, but not sure if DB_affected_rows() will be OK, as it might be that pricematrix table is empty, then DB_affected_rows() will return 0, but the update query was succesful too.

I think:

```
if (DB_error_no() == 0) {
	UpdateDBNo(basename(__FILE__, '.php'), _('Default end date for price matrix set to 9999-12-31'));
}
```

Will do the trick in all cases.
BTW, I also changed the success message that was wrong.

**Comment by timschofield** [comment]
Actually looking at this with fresh eyes this morning, I think we need
to test whether $_SESSION['Updates']['Errors'] is zero here.This holds
the number of errors that were detected during the update, and we
should maybe not update the DBUpdateNo config variable if there were
any errors.

Thanks
Tim

On Sun, 15 Dec 2024 at 23:10, pakricard ***@***.***> wrote:
>
> Hi @timschofield :
> Thanks for pointing it out.
> DB_num_rows() was wrong, but not sure if DB_affected_rows() will be OK, as it might be that pricematrix table is empty, then DB_affected_rows() will return 0, but the update query was succesful too.
>
> I think:
>
> if (DB_error_no() == 0) {
> UpdateDBNo(basename(__FILE__, '.php'), _('Default end date for price matrix set to 9999-12-31'));
> }
>
> Will do the trick in all cases.
> BTW, I also changed the success message that was wrong.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/

**Comment by timschofield** [comment]
I agree, that's why I was talking about using
$_SESSION['Updates']['Errors'] as the check. This is the number of
errors that Z_UpgradeDatabase.php has found while running that script.
Ideally the individual files should only use functions that are in the
includes/UpgradeDB_XXXX.php scripts. In the case of 12.php I would
have used UpdateField().

This is important as the updates are then DBMS independent (mariadb
and mysql are starting to diverge, and I still retain the ambition to
make webERP work on postgres) and also the functions are doing some
sanity checks lessening the chances that the update will do damage to
the database.

I think all the update files should end with:

if ($_SESSION['Updates']['Errors'] == 0) {
    UpdateDBNo(basename(__FILE__, '.php'), _('Message stating what the
update does'));
}

Then as you say the config field won't be updated.

Tim


On Mon, 16 Dec 2024 at 09:23, pakricard ***@***.***> wrote:
>
> I committed this change, but I am not confident with this new update system. Logically, if any of the SQL instructions during the process of DB update fails, we should not change the DBUpdateNumber; otherwise we would be assuming it went OK.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
www.weberp.org
@TimSchofield2
Blog: https://kwamoja.home.blog/
