### ISSUE TITLE
Unable to select Location when adding Item to BOM

### ISSUE THREAD

**Issue by dalers** [timschofield/webERP#322]
When adding an Item to a BOM, the Location must be selected, but no selections are listed.

![image](https://github.com/user-attachments/assets/3a14e8b3-c187-4114-8517-8667165ac10c)

However, there are locations in [Main Menu > Setup > Inventory Setup > Inventory Locations Maintenance]. Does some other location need to be setup?

![image](https://github.com/user-attachments/assets/17a183da-7730-4c5f-8a94-007dc6571b3d)

**Comment by pakricard** [comment]
Have you granted access rights

**Comment by dalers** [comment]
Thanks Tim, I suspect you are correct, I'll find out for sure in the morning. :-)

**Comment by timschofield** [comment]
This one was down to Ricard!

**Comment by dalers** [comment]
My apologies @pakricard! Too late at night to think straight.

However (now in the morning), I checked [Inventory Location Authorized Users Maintenance] and added user nnewton to [User Authorized Inventory Locations Maintenance] but still there are still no locations listed when ading an Item to a BOM.

Is there anything else I can check? 

![2024-12-21 12_42_21 authorized users for shopton factory](https://github.com/user-attachments/assets/6af1b53f-194f-48cb-ae76-a19460e06fa4)

![2024-12-21 13_02_31-Window](https://github.com/user-attachments/assets/c2195f21-b02c-4b01-b2c6-0d7f70062c44)

**Comment by dalers** [comment]
I'm still poking around trying to troubleshoot. I don't think they're related, but fwiw I noticed Chrome reported a HTML and a Javascript error.

![image](https://github.com/user-attachments/assets/8dc34662-f143-4876-a7e0-075c76251ed8)

**Comment by pakricard** [comment]
No worries at all, @dalers .
Then, you might need to set the location as "Work centre"
![image](https://github.com/user-attachments/assets/dade6593-6d09-45b8-afcc-7fb1763f4c6e)

**Comment by dalers** [comment]
Hi @pakricard, thanks for your suggestion but I had already created a "DEF" ("Default") work centre. I'm at a loss understanding what I'm missing or have done incorrectly. Can you spare some time to login to my site and check the configuration? If you add an email address to your GitHub profile I could email you an Administrator username and password, or if you prefer can send some other way (e.g. via LinkedIn if you send me a networking invitation).

If the config isn't the problem, my next guess would be an issue with the db, perhaps resulting from an issue in one of the db upgrades.

Cheers,
Dale

![image](https://github.com/user-attachments/assets/68921090-4c36-42d9-ba5f-6a9e77ee5410)

**Comment by dalers** [comment]
Fwiw, I ran the LocCode SQL query from BOMs.php (line 522) without UserID and no rows were returned.

```
SELECT locationname, locations.loccode
FROM locations
INNER JOIN locationusers
ON locationusers.loccode=locations.loccode
AND locationusers.canupd=1
WHERE locations.usedforwo = 1;
```

I'm guessing this _should_ have returned something...  (if I understand the query correctly)

**Comment by dalers** [comment]
Further removing "WHERE locations.usedforwo = 1" returns 24 rows, so I'm guessing there's a problem with "usedforwo"...

```
SELECT locationname, locations.loccode
FROM locations
INNER JOIN locationusers
ON locationusers.loccode=locations.loccode
AND locationusers.canupd=1;
```

![image](https://github.com/user-attachments/assets/69a41cd5-2790-4cd0-909f-878d19e9e5f1)

**Comment by dalers** [comment]
Doh! Cause was user error - the Location was not configured to allow work orders for production. Thanks @pakricard for your moral support to see this through. :-)

BOMs In webERP specifiy the location that will be used for production (i.e. if an item can be produced in more than one location, a BOM must be created for each location). 

![image](https://github.com/user-attachments/assets/6e3e6f1d-6ebe-446e-88f9-ddbb7f913d7b)
